
services:
  mongodb:
    image: mongo:7.0
    container_name: springboot-m
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mongo-data:
